// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaWMiuJVhsoOV493zOuIW44kjlQHKskQ',
    appId: '1:332930851519:web:1e3715b792bb26b4861c0a',
    messagingSenderId: '332930851519',
    projectId: 'polybudget-80e2b',
    authDomain: 'polybudget-80e2b.firebaseapp.com',
    storageBucket: 'polybudget-80e2b.appspot.com',
    measurementId: 'G-C8LVDDFB97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTZtdqkCxmaEXDpp1PDmWmB3dXmuwjgDA',
    appId: '1:332930851519:android:1b503073c094570e861c0a',
    messagingSenderId: '332930851519',
    projectId: 'polybudget-80e2b',
    storageBucket: 'polybudget-80e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwn-nOeJ0QmIMN0-tc4PCE2sXpgoN6PI8',
    appId: '1:332930851519:ios:48a0ab79bc0ffad1861c0a',
    messagingSenderId: '332930851519',
    projectId: 'polybudget-80e2b',
    storageBucket: 'polybudget-80e2b.appspot.com',
    iosClientId: '332930851519-tar6tujnt3ej7bdptnj73i1321dqm92f.apps.googleusercontent.com',
    iosBundleId: 'com.example.polybudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwn-nOeJ0QmIMN0-tc4PCE2sXpgoN6PI8',
    appId: '1:332930851519:ios:dea919d5224a6190861c0a',
    messagingSenderId: '332930851519',
    projectId: 'polybudget-80e2b',
    storageBucket: 'polybudget-80e2b.appspot.com',
    iosClientId: '332930851519-4g799ac84q2bbsp999qjo9p77gb496h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.polybudget.RunnerTests',
  );
}
